# Generated by Django 4.1.5 on 2023-02-07 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_friend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='sex',
        ),
        migrations.AddField(
            model_name='users',
            name='adress',
            field=models.CharField(default='', max_length=100, verbose_name='adress'),
        ),
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=30, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='surname'),
        ),
        migrations.CreateModel(
            name='UserRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('rating', models.IntegerField(verbose_name='rating')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_friend.users')),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='hobbies',
            field=models.ManyToManyField(to='app_friend.hobbies'),
        ),
    ]
